version: "3.9"

services:
  mysql:
    container_name: mysql_container
    image: mysql:8.4
    hostname: ${MYSQL_HOST}
    environment:
#      - MYSQL_DATABASE
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_USER
      - MYSQL_PASSWORD
    ports:
      - "${MYSQL_PORT}:${MYSQL_PORT}"
    command: [ "--max_connections=500" ]
    volumes:
      - ./docker/mysql_init.sql:/docker-entrypoint-initdb.d/mysql_init.sql
      - mysql:/var/lib/mysql
    networks:
      - auction-network
  redis:
    image: redis:7.4
    container_name: redis_container
    hostname: ${REDIS_HOST}
    ports:
      - "${REDIS_PORT}:${REDIS_PORT}"
    volumes:
      - redis:/data
    environment:
      - REDIS_PASSWORD=${REDIS_PASSWORD}
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
  maildev:
    image: maildev/maildev:2.1.0
    container_name: maildev_container
    ports:
      - "1025:1025"
      - "1080:1080"
#    environment:
#      - MAILDEV_SMTP_PORT=1025
#      - MAILDEV_WEB_PORT=1080
#      - MAILDEV_INCOMING_USER=xdpsx
#      - MAILDEV_INCOMING_PASS=xdpsxpass
    restart: always

volumes:
  mysql:
  redis:

networks:
  auction-network:
    driver: bridge
    name: auction-network