CREATE TABLE orders (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    track_number VARCHAR(255) NOT NULL,
    total_amount DECIMAL(15, 2),
    status TINYINT NOT NULL,
    payment_method TINYINT NOT NULL,
    recipient VARCHAR(50) NOT NULL,
    shipping_address VARCHAR(255) NOT NULL,
    mobile_number VARCHAR(20) NOT NULL,
    note VARCHAR(255),
    reason VARCHAR(255),
    created_at DATETIME DEFAULT CURRENT_TIMESTAMP,
    updated_at DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    user_id BIGINT NOT NULL,
    seller_id BIGINT NOT NULL,
    auction_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES users(id),
    FOREIGN KEY (seller_id) REFERENCES users(id),
    FOREIGN KEY (auction_id) REFERENCES auctions(id)
);
